### ISSUE TITLE
eigenvalues from hamiltonian in presence of magnetic field

### ISSUE THREAD

**Issue by masume70** [zerothi/sisl#782] opened 2024-06-03 09:25 UTC
Hi,
Thank you for providing example TB_07, however it is not completely straightforward for me!
I want to extract eigenvalues of graphene hamiltonian in presence of the magnetic field.
Thanks for your help in advanced 
Masoumeh Alihosseini

**Comment by zerothi** [comment] 2024-06-03 09:52
Hi, I don't fully know how to calculate the eigenvalues for systems with magnetic fields (I have never done this).
The problem is that the magnetic field are in the periodic case, whether or not one can do it I don't know. If you find details in litterature, that would be beneficial. :)

**Comment by zerothi** [comment] 2024-07-01 17:57
Let me finalize this:

The Hamiltonian, I guess, should still be Hermitian, so you should be able to do something like this:
```python
H = si.Hamiltonian(...)
# edit H such that it has magnetization
es = H.eigenstate()
```
Until there is a more specific use-case, or an example, I will close this issue, thanks for opening it up!

**Closed by zerothi** 2024-07-01 17:57 UTC
