### ISSUE TITLE
Berry phase calculation for non orthogonal basis

### ISSUE THREAD

**Issue by pfebrer** [zerothi/sisl#416] opened 2021-12-14 20:03 UTC
From the documentation on `sisl.electron.berry_phase` it seems like non orthogonal basis could be supported, but are not.

Is this true? If so and it is easy to implement, could you do it when you have time? It would be very useful for me to calculate Zak phases from SIESTA hamiltonians.

Thanks!

**Comment by zerothi** [comment] 2021-12-15 06:25
This is a duplicate of #356 and I will close this one, please continue discussion there :)

**Closed by zerothi** 2021-12-15 06:25 UTC
